### PR TITLE
Get complete User object properties

### PR DESCRIPTION
**Pull request by kejkz**
- [x] Serialize profile properties

### CODE REVIEW

**Comment by kejkz** [comment]
@dempfi please take a look when you have time. Thanks.

**Comment by fullofcaffeine** [comment]
Nice one 👍

**Comment by dempfi** [comment]
@kejkz there is already helper to handle camelization of keys, please use it https://github.com/dempfi/xene/blob/master/packages/slack/src/api/converters/camel.ts

**Comment by kejkz** [comment]
@dempfi nice, I'll use that one

**Pull request merged**
